platform: linux

image_resource:
  type: docker-image
  source:
    repository: golang
    tag: 1.10.2

inputs:
- name: src

run:
  path: ./src/ci/scripts/integration-test.sh

params:
  PROJECT_ID:
  TOPIC_NAME:
  SUBSCRIPTION_NAME:
  SERVICE_ACCOUNT:

